name: Trigger Cloudflare Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Pages Deploy Hook
        run: curl -s -X POST "${{ secrets.CF_DEPLOY_HOOK }}"
